name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: [6, 8, 10]
    
    steps:
    - uses: actions/checkout@v1
    - name: Python Style Checker
      uses: andymckay/pycodestyle-action@0.1.3
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: 'Say the cow'
      uses: mscoutermarsh/cowsays-action@🐮
      with:
        args: ${{ matrix.node_version }}
