name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node: [6, 8, 10]
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - run: ls
    - name: 'Checking out the with keyword'
      uses: docker://debian:stretch-slim
      with:
        awesome_variable: Such a good input
        entrypoint: /bin/echo
        args: $INPUT_AWESOME_VARIABLE
        version: $
    - name: 'Say the cow'
      uses: mscoutermarsh/cowsays-action@🐮
      with:
        version: $
